asdasdsa

diff --git a/.github/workflows/build-ami.yml b/.github/workflows/build-ami.yml
--- a/.github/workflows/build-ami.yml
+++ b/.github/workflows/build-ami.yml
@@ -22,14 +22,14 @@ jobs:
     - name: Set up Google Cloud SDK
       uses: google-github-actions/setup-gcloud@v0.2.0
       with:
-        service_account_key: ${{ secrets.GCP_SA_KEY }}
-
-    - name: Check Service Account Key File
-      run: |
-        if [ ! -f "${{ github.workspace }}/secrets/project4-414017-5c44874f2950.json" ]; then
-          echo "Error: Service account key file not found."
-          exit 1
-        fi
+        credentials_json: ${{ secrets.GCP_SA_KEY }}
+    
+    # - name: Check Service Account Key File
+    #   run: |
+    #     if [ ! -f "${{ github.workspace }}/secrets/project4-414017-5c44874f2950.json" ]; then
+    #       echo "Error: Service account key file not found."
+    #       exit 1
+    #     fi
 
     - name: Set up environment variables
       run: |
