B2 (#39)
* userfile added

* test pushing

* ass2

* adding put method

* pushing new files

* removing kerys

* changed the file

* changed the file

* changed the file

* sdsad

* sdsad

* sasdsaad

* sasdsaad

* sasdsaad

* sasdsaad

* sasdsaad

* sasdsaad

* assad

* assad

* assad

* assad

* workflow

* asda

* asdsa

* asdsa

* asdsa

* asdsad

* asdsad

* asdsad

* asdsad

* asdsad

* asdsad

* adsad

* adsad

* adsad

* adsad

* adsad

diff --git a/.github/workflows/build-ami.yml b/.github/workflows/build-ami.yml
--- a/.github/workflows/build-ami.yml
+++ b/.github/workflows/build-ami.yml
@@ -24,6 +24,13 @@ jobs:
       with:
         service_account_key: ${{ secrets.GCP_SA_KEY }}
 
+    - name: Check Service Account Key File
+      run: |
+        if [ ! -f "${{ github.workspace }}/secrets/project4-414017-5c44874f2950.json" ]; then
+          echo "Error: Service account key file not found."
+          exit 1
+        fi
+
     - name: Set up environment variables
       run: |
         export GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/secrets/project4-414017-5c44874f2950.json
